import type { WalnutContext } from './walnut';

/** @walnut_method
 * name: POST CDC-BBM Job API
 * description: Read batch from $[batch] and POST cdc-bbm job to ${url}
 * actionType: custom_post_cdc_bbm_job
 * context: api
 * needsLocator: false
 * category: API Testing
 */
export async function postCdcBbmJob(ctx: WalnutContext) {
  // ctx.args[0] = "batch" (from $[batch]) — runtime variable name to READ the batch generated by transform job
  // ctx.args[1] = API URL (from ${url})

  const batchVarName = ctx.args[0];
  const url = ctx.args[1];

  // Read batch from runtime variable (same value generated by transform job)
  const batch = ctx.getVariable(batchVarName);
  if (!batch) {
    throw new Error(
      'Batch not found in runtime variable "' + batchVarName + '". Ensure the transform job ran first.'
    );
  }
  ctx.log('Using existing batch: ' + batch);

  // Build request body
  const body = {
    batch: batch,
    mode: 'individual',
    job_type: 'cdc-bbm',
    extra_args: { RECORD_RETENTION_YEARS: '20' },
  };

  ctx.log('POST ' + url + ' with body: ' + JSON.stringify(body));

  const response = await ctx.post(url, body);
  ctx.assertStatus(response, 200);

  ctx.log('POST successful. Status: ' + response.status);
  ctx.log('Response body: ' + JSON.stringify(response.body));
}
