import type { WalnutBaseContext } from './walnut';
import * as path from 'path';
import * as fs from 'fs';
import { spawnSync } from 'child_process';

/** @walnut_method
 * name: Claim2 ActualFile Artifact Upload Reuse MemberID Replace Upload 1 File
 * description: Reuse generated member ID $[memberId], replace {{member_id}} in artifact ${claim2Artifact} and upload to /TO_AVER/ via SFTP host ${sftphost} port ${sftpport} user ${sftpusername} password ${sftppassword} using batch $[batch]
 * actionType: custom_reuse_memberid_artifact_replace_upload_1file
 * context: shared
 * needsLocator: false
 * category: File Transfer
 */
export async function reuseMemberIdArtifactReplaceUpload1File(ctx: WalnutBaseContext) {
  // ctx.args[0] = "memberId" (from $[memberId]) — reads the member ID generated by Method 1
  // ctx.args[1] = claim2Artifact (from ${claim2Artifact}) — artifact ref for the 3rd file
  // ctx.args[2] = SFTP host (from ${sftphost})
  // ctx.args[3] = SFTP port (from ${sftpport})
  // ctx.args[4] = SFTP username (from ${sftpusername})
  // ctx.args[5] = SFTP password (from ${sftppassword})
  // ctx.args[6] = "batch" (from $[batch]) — reads the batch value stored by Method 1

  const memberId = ctx.getVariable(ctx.args[0]);
  const artifactRef = ctx.args[1];
  const host = ctx.args[2];
  const port = ctx.args[3] || '22';
  const username = ctx.args[4];
  const password = ctx.args[5];
  const batch = ctx.getVariable(ctx.args[6]);

  if (!memberId) {
    throw new Error(
      'memberId runtime variable not found. Ensure the "Generate Member ID Artifact Replace and Upload 2 Files" step ran first.'
    );
  }
  ctx.log('Using existing member ID from previous step: ' + memberId);

  if (!artifactRef) {
    throw new Error('Artifact reference is required for the file to upload.');
  }

  if (!host || !username || !password) {
    throw new Error(
      'SFTP credentials missing. Ensure sftphost, sftpusername, and sftppassword are set in test data.'
    );
  }

  const remoteDirectory = '/TO_AVER/';
  const tempDir = process.env.TEMP || '/tmp';

  // Step 1: Resolve artifact reference to a local file path
  ctx.log('Processing artifact: ' + artifactRef);
  const filePath = await ctx.resolveArtifact(artifactRef);
  ctx.log('Resolved artifact to: ' + filePath);

  if (!fs.existsSync(filePath)) {
    throw new Error('Artifact file not found at resolved path: ' + filePath);
  }

  // Read the original artifact file (original artifact is NEVER modified)
  const originalContent = fs.readFileSync(filePath, 'utf-8');

  // Step 2: Replace all occurrences of {{member_id}} with the same member ID from Method 1
  const updatedContent = originalContent.replace(/\{\{member_id\}\}/g, memberId);

  const replacedCount = (originalContent.match(/\{\{member_id\}\}/g) || []).length;
  if (replacedCount > 0) {
    ctx.log('Replaced ' + replacedCount + ' {{member_id}} placeholder(s) with ' + memberId);
  } else {
    ctx.warn('No {{member_id}} placeholders found in artifact');
  }

  // Step 3: Build filename with shifted timestamp (2699 days forward)
  // Format: baseName_YYYYMMDDHHmmss_epochMillis.ext
  const fileNow = new Date();
  const fileShifted = new Date(fileNow.getTime() + 2699 * 24 * 60 * 60 * 1000);
  const fYyyy = fileShifted.getFullYear().toString();
  const fMM = (fileShifted.getMonth() + 1).toString().padStart(2, '0');
  const fdd = fileShifted.getDate().toString().padStart(2, '0');
  const fHH = fileShifted.getHours().toString().padStart(2, '0');
  const fmm = fileShifted.getMinutes().toString().padStart(2, '0');
  const fss = fileShifted.getSeconds().toString().padStart(2, '0');
  const fileDateTimeStamp = fYyyy + fMM + fdd + fHH + fmm + fss;
  const fileEpochMillis = fileNow.getTime().toString();

  if (batch) {
    ctx.log('Using batch from previous step: ' + batch);
  }

  const originalExt = path.extname(filePath) || '.csv';
  const originalBase = path.basename(filePath, originalExt);
  // Strip ALL trailing _digits groups from the original filename (remove old timestamps)
  let baseName = originalBase;
  while (/_\d+$/.test(baseName)) {
    baseName = baseName.replace(/_\d+$/, '');
  }
  const fileName = baseName + '_' + fileDateTimeStamp + '_' + fileEpochMillis + originalExt;

  // Write modified content to temp file (original artifact stays untouched)
  const tempFilePath = path.join(tempDir, fileName);
  fs.writeFileSync(tempFilePath, updatedContent, 'utf-8');
  ctx.log('Created temp file: ' + fileName);

  // Step 4: Upload temp file via SFTP to /TO_AVER/
  const remotePath = remoteDirectory + fileName;
  ctx.log('Uploading to ' + host + ':' + remotePath + '...');

  const pyScript = [
    'import paramiko',
    'import sys',
    '',
    'host = sys.argv[1]',
    'port = int(sys.argv[2])',
    'username = sys.argv[3]',
    'password = sys.argv[4]',
    'local_file = sys.argv[5]',
    'remote_path = sys.argv[6]',
    '',
    'transport = paramiko.Transport((host, port))',
    'transport.connect(username=username, password=password)',
    'sftp = paramiko.SFTPClient.from_transport(transport)',
    '',
    'try:',
    '    sftp.put(local_file, remote_path)',
    '    print("Upload successful: " + remote_path)',
    'finally:',
    '    sftp.close()',
    '    transport.close()',
  ].join('\n');

  const tmpScript = path.join(tempDir, 'sftp_upload_1artifact_post_betl_' + Date.now() + '.py');

  try {
    fs.writeFileSync(tmpScript, pyScript);

    // Credentials passed as arguments — never written to any file
    const result = spawnSync('python', [
      tmpScript,
      host,
      port,
      username,
      password,
      tempFilePath,
      remotePath,
    ], {
      timeout: 180000,
      encoding: 'utf-8',
    });

    if (result.error) {
      throw new Error('Python execution error: ' + result.error.message);
    }

    if (result.status !== 0) {
      throw new Error('SFTP upload failed: ' + (result.stderr || result.stdout));
    }

    ctx.log('Successfully uploaded file to ' + remotePath);
    ctx.log(result.stdout);
  } finally {
    // Cleanup: remove temp Python script and temp data file
    if (fs.existsSync(tmpScript)) fs.unlinkSync(tmpScript);
    if (fs.existsSync(tempFilePath)) fs.unlinkSync(tempFilePath);
  }
}
