import type { WalnutContext } from './walnut';
import * as path from 'path';
import * as fs from 'fs';
import { spawnSync } from 'child_process';

/** @walnut_method
 * name: Replace ICMEM and Upload Single File
 * description: Replace {{member_id}} with $[icmemId] in template ${localFilePath} with SFTP host ${sftpHost} port ${sftpPort} user ${sftpUsername} password ${sftpPassword} and upload to /TO_AVER/
 * actionType: custom_sftp_template_upload
 * context: shared
 * needsLocator: false
 * category: File Transfer
 */
export async function sftpTemplateUpload(ctx: WalnutContext) {
  // ctx.args[0] = "icmemId" (from $[icmemId]) — reads existing runtime variable from Step 1
  // ctx.args[1] = file path from ${localFilePath}
  // ctx.args[2] = SFTP host from ${sftpHost}
  // ctx.args[3] = SFTP port from ${sftpPort}
  // ctx.args[4] = SFTP username from ${sftpUsername}
  // ctx.args[5] = SFTP password from ${sftpPassword}

  // Read the ICMEM ID generated by Step 1 (do NOT generate a new one)
  const icmemId = ctx.getVariable(ctx.args[0]);
  if (!icmemId) {
    throw new Error('icmemId runtime variable not found. Ensure Step 1 (Generate ICMEM ID) ran successfully before this step.');
  }
  ctx.log('Using existing ICMEM ID from Step 1: ' + icmemId);

  const localFilePath = ctx.args[1];
  const host = ctx.args[2];
  const port = ctx.args[3] || '22';
  const username = ctx.args[4];
  const password = ctx.args[5];
  const remoteDirectory = '/TO_AVER/';

  if (!host || !username || !password) {
    throw new Error('SFTP credentials missing. Ensure sftpHost, sftpUsername, and sftpPassword are set in test data.');
  }

  if (!localFilePath) {
    throw new Error('localFilePath parameter is empty. Ensure the file path is set in test data.');
  }

  ctx.log('Template file path: ' + localFilePath);

  // Verify the file exists
  if (!fs.existsSync(localFilePath)) {
    throw new Error('Template file not found at path: ' + localFilePath);
  }

  // Read the template file and replace {{member_id}} with the ICMEM ID (original file is NOT modified)
  const templateContent = fs.readFileSync(localFilePath, 'utf-8');
  const updatedContent = templateContent.replace(/\{\{member_id\}\}/g, icmemId);

  // Generate filename with date shifted 2,672 days forward in YYYYMMDDHHMMSS format + milliseconds timestamp
  const now = new Date();
  const shifted = new Date(now.getTime() + 2672 * 24 * 60 * 60 * 1000);
  const yyyy = shifted.getFullYear().toString();
  const MM = (shifted.getMonth() + 1).toString().padStart(2, '0');
  const dd = shifted.getDate().toString().padStart(2, '0');
  const HH = shifted.getHours().toString().padStart(2, '0');
  const mm = shifted.getMinutes().toString().padStart(2, '0');
  const ss = shifted.getSeconds().toString().padStart(2, '0');
  const dateStamp = yyyy + MM + dd + HH + mm + ss;
  const millis = now.getTime().toString();
  const originalExt = path.extname(localFilePath) || '.csv';
  const originalBase = path.basename(localFilePath, originalExt);
  const fileName = originalBase + '_' + dateStamp + '_' + millis + originalExt;
  const tempDir = process.env.TEMP || '/tmp';
  const modifiedFilePath = path.join(tempDir, fileName);

  // Write modified content to temp file (original stays untouched)
  fs.writeFileSync(modifiedFilePath, updatedContent, 'utf-8');

  ctx.log('Replaced {{member_id}} with ' + icmemId + ' in temp file');
  ctx.log('Generated timestamp filename: ' + fileName);

  // Upload modified temp file via SFTP to /TO_AVER/
  const remotePath = remoteDirectory + fileName;
  ctx.log('Uploading to ' + host + ':' + remotePath + '...');

  const pyLines = [
    'import paramiko',
    'import sys',
    '',
    'host = sys.argv[1]',
    'port = int(sys.argv[2])',
    'username = sys.argv[3]',
    'password = sys.argv[4]',
    'local_file = sys.argv[5]',
    'remote_path = sys.argv[6]',
    '',
    'transport = paramiko.Transport((host, port))',
    'transport.connect(username=username, password=password)',
    'sftp = paramiko.SFTPClient.from_transport(transport)',
    '',
    'try:',
    '    sftp.put(local_file, remote_path)',
    '    print("Upload successful: " + remote_path)',
    'finally:',
    '    sftp.close()',
    '    transport.close()',
  ];

  const pyScript = pyLines.join('\n');
  const tmpScript = path.join(tempDir, 'sftp_upload_' + Date.now() + '.py');

  try {
    fs.writeFileSync(tmpScript, pyScript);

    const result = spawnSync('python', [
      tmpScript,
      host,
      port,
      username,
      password,
      modifiedFilePath,
      remotePath
    ], {
      timeout: 120000,
      encoding: 'utf-8',
    });

    if (result.error) {
      throw new Error('Python execution error: ' + result.error.message);
    }

    if (result.status !== 0) {
      throw new Error('SFTP upload failed: ' + (result.stderr || result.stdout));
    }

    ctx.log('Successfully uploaded file to ' + remotePath);
    ctx.log(result.stdout);
  } finally {
    // Cleanup temp files
    if (fs.existsSync(tmpScript)) fs.unlinkSync(tmpScript);
    if (fs.existsSync(modifiedFilePath)) fs.unlinkSync(modifiedFilePath);
  }
}
